name: .NET Core Desktop Simple Workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest  

    env:
      Solution_Name: TourGuide.sln
      Test_Project_Path: TourGuideTest/TourGuideTest.csproj

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Build solution
      run: dotnet build ${{ env.Solution_Name }} --configuration ${{ matrix.configuration }}

    - name: Execute unit tests
      run: dotnet test ${{ env.Test_Project_Path }} --configuration ${{ matrix.configuration }}

    - name: Publish application
      run: dotnet publish ${{ env.Solution_Name }} --configuration ${{ matrix.configuration }} --output ./artifacts

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Application Package
        path: ./artifacts
